version: "3"
services:
    web:
        build: ClientService.Server
        container_name: 'clients-service-api'
        ports:
            - 5000:80
        restart: always
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: 'clients-service-mongodb'
        volumes:
            - data/db var/data/db
    front:
        build: ClientService.UI
        container_name: 'clients-service-ui'
        ports:
            - 3000:80
        restart: always
        depends_on:
            - web